language: python
python:
  - "3.5"
cache:
  directories:
    - $HOME/.cache/pip
addons:
  postgresql: "9.4"

before_install:
  - pip install flake8 coverage

before_script:
  - python3 -m flake8 .
  - psql -c 'create database demo;' -U postgres
  - head -c 24 /dev/urandom > COOKIE_SECRET

script:
  - ./tests/tests_with_coverage.sh
